language: go
sudo: false

cache:
  directories:
    - ${GOPATH}/src/github.com/fatih
    - ${GOPATH}/src/github.com/golang
    - ${GOPATH}/src/github.com/h12w
    - ${GOPATH}/src/github.com/mattn
    - ${GOPATH}/src/github.com/stretchr
    - ${GOPATH}/src/golang.org

go:
  - 1.7
  - 1.6

go_import_path: github.com/steenzout/go-log

env:
  - GLIDE_VERSION="0.12.3"

install:
  - mkdir "${GOPATH}/bin"
  - wget "https://github.com/Masterminds/glide/releases/download/v${GLIDE_VERSION}/glide-v${GLIDE_VERSION}-linux-amd64.tar.gz"
  - mkdir -p "${GOPATH}/bin"
  - tar -vxz -C "${GOPATH}/bin" --strip=1 -f "glide-v${GLIDE_VERSION}-linux-amd64.tar.gz"
  - export PATH="${GOPATH}/bin:$PATH"
  - glide install
  - go get github.com/h12w/gosweep
  - go get github.com/mattn/goveralls

script:
  - go test -v ./...

after_success:
  - bash ${GOPATH}/src/github.com/h12w/gosweep/gosweep.sh
  - ${HOME}/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci

