language: go
cache:
  apt: true
  directories:
    - ${GOPATH}/src/github.com/stretchr
sudo: false
go:
  - 1.5
go_import_path: github.com/mediaFORGE/gol


install:
  - go get github.com/stretchr/testify

script:
  - go test -cover ./...
